### ISSUE TITLE
Footer Attributions

### ISSUE THREAD

**Issue by HighDynamics** [kcbryan10/View-Dine-Randomizer#14]
# API attributions in the footer
We need to add attributions to the two APIs we are using, here's how they want us to do that

# Edamam
From their site:
> Place this inside the HEAD section of your page.
> <script src="https://developer.edamam.com/attribution/badge.js"></script>
> 
> Place this exactly where you want the badge to show.
> <div id="edamam-badge" data-color="white"></div>

# TMDB
From their site:
> You shall use the TMDB logo to identify your use of the TMDB APIs.
>
> You shall place the following notice prominently on your application: "This product uses the TMDB API but is not endorsed or certified by TMDB."
>
> Any use of the TMDB logo in your application shall be less prominent than the logo or mark that primarily describes the application and your use of the TMDB logo shall not imply any endorsement by TMDB.

Link to their logos: https://www.themoviedb.org/about/logos-attribution

**Comment by kcbryan10** [comment]
footer with atributions to API complete
